#!/bin/bash
set -e

usage() {
  echo "usage: $0 [channel/]<package> ..."
  echo "   ie: $0 uploadprogress oauth-1.2.3"
}

if [ $# -eq 0 ]; then
  usage >&2
  exit 1
fi

if [ $1 -eq "big_int" ]; then
    mkdir -p /tmp/temp__$1
    cd /tmp/temp__$1
    wget https://pecl.php.net/get/big_int-1.0.7.tgz
    tar zxf big_int-1.0.7.tgz
    cd big_int-1.0.7
    phpize
    ./configure
    make
    make install
else
    pecl install "$@"
fi

while [ $# -gt 0 ]; do
  ext="$1"
  ext=$(echo "$ext" | cut -d- -f1)
  ext=$(echo "$ext" | cut -d\/ -f2)
  shift

  for module in $(find /usr/local/lib/php/extensions -name "$ext.so"); do
    ini="$PHP_INI_DIR/conf.d/docker-php-pecl-$ext.ini"

    if grep -q zend_extension_entry "$module"; then
      # https://wiki.php.net/internals/extensions#loading_zend_extensions
      line="zend_extension=$(basename "$module")"
    else
      line="extension=$(basename "$module")"
    fi

    if [ ! -f $ini ]; then
        touch $ini
    fi

    if ! grep -q "$line" "$ini" 2>/dev/null; then
      echo "$line" >> "$ini"
    fi
  done
done

rm -rf /tmp/*
